### ISSUE TITLE
Address should be plain street address

### ISSUE THREAD

**Issue by henare** [PuZZleDucK/Bega_Valley_Applications_on_Exhibition#1]
Addresses are geocoded by PlanningAlerts using the Google geocoder so the address field needs to be tidied up a bit. This is also useful for other people that might be using the data.

e.g.

> Lot: 3 DP: 39004-60 Main Street MERIMBULA

should be 

> 60 Main Street MERIMBULA

it's probably worth also adding the state, so:

> 60 Main Street MERIMBULA, NSW

**Comment by PuZZleDucK** [comment]
I've thought about parsing a similar issue with addresses recently and erred on the side of preservation... the bit of the address "39004-60" would be awkward to parse cleanly without dropping a legitimate range address like "22-24" ... would a rule of thumb like "house # ranges are at most 20", so 22-44 passes but 39004-60 takes the last value sound ok? should the maximum range be higher, maybe 200? or am I over thinking and just the last number is ok for geo-coding?

Adding the state is a no brainer, will do.

**Comment by equivalentideas** [comment]
>  "house # ranges are at most 20", so 22-44 passes but 39004-60 takes the last value sound ok? should the maximum range be higher, maybe 200? or am I over thinking and just the last number is ok for geo-coding?

Hi @PuZZleDucK , I think if possible it would be good to get the address range because it gives people some useful information about the building they're reading about, “is it apartments?”. Ranges always start with a lower number, then a higher one. You could test if the number before the dash is lower?

**Comment by PuZZleDucK** [comment]
Aww... that's a great solution, unfortunately it was even worse and I had to resort to relying on how they have formatted the data. I'm guessing that's just a fact of life with semi-structured data. Still should capture a range address ok.
In any case the address now begins with the number (if it's even there! ahhh) and has the state tacked onto the end (b31399aca1853c7ab4f7e3f7009b78f8c2955691).
Thanks for the feedback.

**Comment by equivalentideas** [comment]
Nice one :+1:
