### ISSUE TITLE
Add on_notice_to

### ISSUE THREAD

**Issue by henare** [PuZZleDucK/Bega_Valley_Applications_on_Exhibition#2]
In the [terribly unstructured] detail page for each application there does appear to be an `on_notice_to` date, e.g.

> If you would like to comment on the proposal please write to us before 11 December 2015.

on http://www.begavalley.nsw.gov.au/cp_themes/default/page.asp?p=DOC-MAK-23-07-78

This is just a nice-to-have feature request. Maybe it's too hard/unreliable to extract? :smile:

**Comment by PuZZleDucK** [comment]
Turns out this was the "easy" one... should be fixed in the latest revision (currently: 0647ebe0553239d29546bdac75e04f42b2a6b7c6)
