### ISSUE TITLE
Get more applications for another listings page

### ISSUE THREAD

**Issue by equivalentideas** [PuZZleDucK/Bega_Valley_Applications_on_Exhibition#3]
I just came across this page with more applications http://www.begavalley.nsw.gov.au/cp_themes/default/page.asp?p=DOC-JDH-32-26-07.

No way to tell if they're still 'on notice' unfortunately, but I assume they aren't because they aren't listed on that ['on exhibition' page](http://www.begavalley.nsw.gov.au/cp_themes/default/page.asp?p=DOC-SBX-15-00-61). Could be worth calling the council and asking why they put different applications on different pages. Could even suggest they put the 'on notice till' date on this new index page.

I think it's worth getting the records from there too. What do you think @PuZZleDucK ?

**Comment by PuZZleDucK** [comment]
I've hacked together the scraper for that second page now live f1bc2d215a7b99c202d5cc9f9263d7d683d48797 ... definitely worth having in there (even some overlap).

I've just used the same email address as the contact and the main page as the info_url field as they don't have individual pages.

**Comment by equivalentideas** [comment]
Nice one @PuZZleDucK  :+1:
