### ISSUE TITLE
No longer scraping due to changed system / disclaimer

### ISSUE THREAD

**Issue by CloCkWeRX** [PuZZleDucK/Bega_Valley_Applications_on_Exhibition#4]
https://www.planningalerts.org.au/authorities/bega

The new place to look seems to be:
http://datracker.begavalley.nsw.gov.au/Home/Disclaimer

**Comment by CloCkWeRX** [comment]
There's an ATDIS feed (http://datracker.begavalley.nsw.gov.au/ATDIS/1.0/applications.json) as part of https://github.com/openaustralia/planningalerts/issues/920

**Comment by henare** [comment]
Fixed in https://github.com/planningalerts-scrapers/Bega_Valley_Applications_on_Exhibition/pull/4

**Comment by PuZZleDucK** [comment]
I've been trying to fix this for a while... just noticed that it's running again on morph.io... I assume no action is required to fix now?

**Comment by CloCkWeRX** [comment]
Got it in one
